/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-mwyaX-qOSoL07RZsxv-GAW2YM3nHj7tHxGjKUl1yDvofJwKxShiVeqqf02lgPSah1C6boeevE27R07nAKLVt9nSG4qkua5XQc588RtYJrDvoNt0KIwsb-7bW",
  "tt": "tt-1-WxChC54NkTr--MRRLs3PT4IYKKix2yyn3OJ3NsAXOXo=",
  "version": "2020-11-20"
}

export default ebconfig;